# Generated by Django 4.2.2 on 2023-06-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_availability_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
